#!/bin/bash
echo "install catalogue \t"
yum install nodejs make gcc-c++ -y

echo "Configuration of catalogue "
useradd roboshop
sudo curl -s -L -o /tmp/catalogue.zip "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
cd /home/roboshop && sudo unzip /tmp/catalogue.zip && sudo mv catalogue-main catalogue && cd /home/roboshop/catalogue && sudo npm install
sudo mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service

echo "service configuration"
systemctl daemon-reload && systemctl start catalogue && systemctl enable catalogue
