#!/bin/bash

PRINT "setting up repository\t"
echo '[mongodb-org-4.2]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc' >/etc/yum.repos.d/mongodb.repo
STATUS_CHECK $?

echo "installation of mongo DB"
yum install -y mongodb-org
systemctl enable mongod && systemctl start mongod && systemctl restart mongod

echo "Creation schema for Mongo DB"

sudo curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
cd /tmp && sudo unzip mongodb.zip && cd mongodb-main && mongo < catalogue.js && mongo < users.js

sed -i -e 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
STATUS_CHECK $?  
