#!/bin/bash
LOG=/tmp/roboshoplog

echo "Downloading SQL repo"
echo '[mysql57-community]
 name=MySQL 5.7 Community Server
 baseurl=http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
 enabled=1
 gpgcheck=0' > /etc/yum.repos.d/mysql.repo
 if [ $? =0 ];then
 echo "installation of SQL"
  yum install mysql-community-server -y
  else
  echo "installation of SQL failed"
  exit 1
  fi
echo "SQL service status"
systemctl enable mysqld  && systemctl start mysqld
echo $?