#!/bin/bash
echo "Redis installation /t"
yum install epel-release yum-utils -y
yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
yum-config-manager --enable remi
echo $?

echo "update redis config"
sed -i -e '/s/127.0.0.0/0.0.0.0' /etc/redis.conf /etc/redis/redis.conf

echo "Redis service configuration /t"
yum install redis -y && systemctl enable redis && systemctl start redis
echo $?
